exp:
  expname: IXI075-Guys-0754-T1_50views_20260210
  expdir: ./logs/
  datadir: /home/czfy/IXI_dataset/IXI_downsampledx4_iacl_SyN/IXI075-Guys-0754/data_50views.pickle
network:
  net_type: mlp
  num_layers: 4
  hidden_dim: 32
  skips: [2]
  out_dim: 1
  last_activation: sigmoid
  bound: 0.3
encoder:
  encoding: hashgrid
  input_dim: 3
  num_levels: 16
  level_dim: 2
  base_resolution: 16
  log2_hashmap_size: 19
render:
  n_samples: 512
  n_fine: 0
  perturb: True
  raw_noise_std: 0.
  netchunk: 8388608 
train:
  epoch: 375
  n_batch: 1
  n_rays: 32768
  lrate: 0.001
  lrate_gamma: 0.1
  lrate_step: 188
  resume: False
log:
  i_eval: 25  # Epoch for evaluation
  i_save: 50  # Epoch for saving
